### ISSUE TITLE
[Oct 16 - Oct 29] Viral Spiral Playtests

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/viral-spiral-backend#145]
Lets slow down a bit and schedule playtests with the people who have signed up for this week and who we had to send back on friday.

We should give the people we had to send away on friday first preference and not make them wait very long. I also don't want to call all of them together. Having too many new people is very high stakes which I learnt the hard way last week. So for some sanity, I'd like to schedule many playtests this week with 1,2 new people and rest of the players can be tattle insiders. Lets figure out a time that works for all of us and we can coordinate with the outsiders.

**Comment by tarunima** [comment]
- @BudhiY16 to coordinate with VS team for playtest timings next week. 
- Schedule playtest with external player for Friday.
