### ISSUE TITLE
Viral Spiral Playtests with Gamers and Media Personnel

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/viral-spiral-backend#148]
We have [Studio Oleomingus](https://oleomingus.com/) and Kunal lined up or interested to join our playtests. This might also be a good time to reinvite Manjari(she attended misinfocon playtest) and had said she'd like to play again. Plus we have Tanvi and Gurshabad from the last cohort.
Adhiraj has some game, content and media associated folks in mind who would like to play the game. The following needs to be done : 

- [ ] [Yash, Adhiraj] : Identify suitable candidates and schedule a suitable time for playtest. 
- [ ] [Yash, Adhiraj, Aatman]Conduct 4-6 playtests.  

For each playtest, Adhiraj will host, Yash will coordinate the event, Aatman will be in charge of livestreaming. I am going to be on the backseat and focus on next steps for scalability and would stay away from the actual playtest as much as possible. I will do my due diligence to ensure that you don't face any incident like last time during the playtest but I might not be physically next to a laptop during playtests since I am in kerala. I think its a risk we'll just have to take.

**Comment by dennyabrain** [comment]
We have [Studio Oleomingus](https://oleomingus.com/) and Kunal lined up or interested to join our playtests. This might also be a good time to reinvite Manjari(she attended misinfocon playtest) and had said she'd like to play again. Plus we have Tanvi and Gurshabad from the last cohort.
Adhiraj has some game, content and media associated folks in mind who would like to play the game. The following needs to be done : 

- [ ] [Yash, Adhiraj] : Identify suitable candidates and schedule a suitable time for playtest. 
- [ ] [Yash, Adhiraj, Aatman]Conduct 4-6 playtests.  

For each playtest, Adhiraj will host, Yash will coordinate the event, Aatman will be in charge of livestreaming. I am going to be on the backseat and focus on next steps for scalability and would stay away from the actual playtest as much as possible. I will do my due diligence to ensure that you don't face any incident like last time during the playtest but I might not be physically next to a laptop during playtests since I am in kerala. I think its a risk we'll just have to take.

**Comment by BudhiY16** [comment]
Adhiraj and Yash have decided to split up the signees of the Playtest form into gamers, media/tech, and others. Our first priority is the gamers, and we have at least two sessions already confirmed. One is with Kunal Sonar (Anushree's contact) and another is a session with Charu Tak and Dhruv from Oleomingus, but this session will only happen after the 10th. Kunal's is happening this Friday. And, in between, when Yash isn't there (from 5-10) Adhiraj will host sessions with those in the media space he knows.

Playtests to happen only on Tuesdays and Fridays, after 5 pm.

Yash and Adhiraj are also drafting an email to be sent to those whom Adhiraj isn't familiar with on the Playtest form to scope out gamers interested in trying the game out.

**Comment by BudhiY16** [comment]
Playtest Calendar - https://docs.google.com/spreadsheets/d/1ly9-BRo_I7k0rYFtAfQgyRzG_w936b2TAFm3SmFYcr8/edit#gid=0

**Comment by dennyabrain** [comment]
Will try to schedule playtests this week.

**Comment by dennyabrain** [comment]
Playtests are happening 
- 1 on Thursday (CDF)
- 1 on Friday (FoV)

**Comment by BudhiY16** [comment]
plan out Viral Spiral playtests for next week and check back on Form responses

**Comment by dennyabrain** [comment]
Halting playtests till adhiraj returns on Jan 5. At which point we will start testing with the new backend.
