### ISSUE TITLE
Let viral spiral share different cards to different people

### ISSUE THREAD

**Issue by RishavT** [tattle-made/viral-spiral-backend#17]
- [ ] Modify the share card action to accept a mapping of card, to for multiple cards
```python3
# maybe something like this
{
    "card": "to_player1",
    "card2": "to_player2",
    "card2": "to_player3",
    # and so on
}
```

- [ ] Write related checks, etc

**Comment by dennyabrain** [comment]
Not sure if this was ever requested by adhiraj. So closing it. Reopen later if this comes up.
