### ISSUE TITLE
Add fact checking / passing restrictions in the backend

### ISSUE THREAD

**Issue by RishavT** [tattle-made/viral-spiral-backend#24]
If card affinity == player affinity, force pass
if card affinity == player affinity, no fact check
same for bias

Currently (in the prototype) these need to be implemented by the frontend. We will need to discuss whether backend limitiation adds to the user experience or not - and accordingly prioritize whether to keep this as a frontend feature or add to the backend.

(Context on the above comment - if we want to show reasons for force pass, for example if we want to tell the player that they need to pass the card because it matches with their affinity, it's better to (also) have this decision making logic - of whether to pass or keep - in the frontend. In that case, the backend restriction just becomes a security feature - which we can do after the initial demo). @dennyabrain let's discuss this sometime.

**Comment by dennyabrain** [comment]
Looks like we don't enforce passing the card of the same affnity as yours anymore. We only penalize them if they don't. So the users need to be alert and not keep a card that agrees with their affinity.
