### ISSUE TITLE
Performance benchmarking

### ISSUE THREAD

**Issue by RishavT** [tattle-made/viral-spiral-backend#4]
- Single user performance
- Multiple user performance

---
- Automated tests for APIs
- Manual testing with throttled APIs 
    - If we expect a scale of 100 users, and with 100 users the 90 percentile API load time is 2 seconds, then we throttle the APIs to take at least 2 seconds and do manual testing in the team
    - Get feedback on how playable the game is with this manual testing and if we need to improve the performance right away.

**Comment by dennyabrain** [comment]
Have created a dedicated milestone of 0.3.0 for this.
