### ISSUE TITLE
"Mark As Fake" power not working as expected

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/viral-spiral-backend#40]
### Scenario A :

If you draw a fake card and you mark it as fake
1. the UI should show a "fake" stamp
2. the card gets discarded automatically

### Scenario B : 
If Player A sends a fake news card to player B and player B marks it as fake, player A loses a point.
1. player B sees a "fake" stamp
2. the card gets discarded automatically

**Comment by RishavT** [comment]
Should be fixed, pushed to main.

Point to note - if B uses the mark as fake power, and the card is NOT a fake, B loses a point (but the card is still discarded).
