### ISSUE TITLE
for every anti red card that is shared, every red player should lose a clout point

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/viral-spiral-backend#44]
I am not sure if this is implemented. Adhiraj said this was added pretty recently so its possible its not implemented.

**Comment by RishavT** [comment]
Done

**Comment by Bhargav-Dave** [comment]
This has been resolved, closing the issue. Refer: https://github.com/tattle-made/viral-spiral-backend/commit/5625b9bbb01874315cd26568bbbf0d189fa68355
