### ISSUE TITLE
Clarify rules for super powers

### ISSUE THREAD

**Issue by Bhargav-Dave** [tattle-made/viral-spiral-backend#69]
Since some of the terminology of the game was changed, there seemed to be some need to clarify the rules for the super powers and it would be great to have a separate section for them in the primary rules overview

**Comment by dennyabrain** [comment]
@Bhargav-Dave see if the new section on Super Powers addresses your concern
https://viralspiral.net/rules

if not, feel free to add your suggestions or what its lacking and we can send it across to adhiraj for rewrites.
