### ISSUE TITLE
Optimize Infinite Loops

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/viral-spiral-backend#74]
I've identified a few infinite loops in the game. Some are surely essential, and some probably can be optimzed to reduce ingame latency The scope of this issue is to 
1. remove any unnecessary infinite loops
2. Identify ways to improve the latency by reducing the time taken by operations that happen within the infinite loops

**Comment by Bhargav-Dave** [comment]
Current latency benchmark updates (average): 

- Create Room (Time taken from pressing the create room button to creation of the room): 10.41 s
- Join Room (Time taken from pressing the join room button to joining the room): 2.09 s
- Pass card (Time taken from pressing the pass card button to the card appearing on another player's screen in a 2 player game): 1.23 s
- Keep card (Time taken from pressing the keep card button to a new card appearing on another player's screen in a 2 player game): 2.79 s

All of these averages are over 10 games (not running simultaneously on the client side but running simultaneously on the server side). I've run the code for 20 games too, but as the games increase, the amount of time required for each action increases by a lot, for instance the time to keep card starts around 1.9 seconds for the first game and increases to around 5.7 seconds for the 10th game.
