### ISSUE TITLE
Authenticate all socket io events using decorator

### ISSUE THREAD

**Issue by RishavT** [tattle-made/viral-spiral-backend#8]
check message["password"] against the password for the game runner

Maybe create a game runner utility function called authenticate() - and call that in the decorator
   - You can set an additional kwarg in the decorator before passing it on to the function - called "game_runner"
   - This way you don't need to load the game runner everytime

Create another decorator to verify that a player has joined a game (their saved client_id is correct)

**Comment by dennyabrain** [comment]
seems like an implementation detail for https://github.com/tattle-made/viral-spiral-backend/issues/12
