### ISSUE TITLE
The last player to receive a card does not get the option to "Mark as Fake" or "Check Source"

### ISSUE THREAD

**Issue by Bhargav-Dave** [tattle-made/viral-spiral-backend#91]

**Comment by Bhargav-Dave** [comment]
@dennyabrain 
Some context on this issue, the "Allowed actions" for the player to recieve the last card for some reason are only "Keep" and "Discard" whereas they should also get "Mark as Fake" and "Check Source"

I think the fix to this is in Player model. Will also investigate myself

**Comment by dennyabrain** [comment]
Thanks this is helpful. I was wondering if its a silly frontend bug but looks like it will need some backend change

**Comment by Bhargav-Dave** [comment]
Turns out it was a silly frontend bug 😛
