### ISSUE TITLE
There should be a penalty for incorrectly using "Mark as Fake"

### ISSUE THREAD

**Issue by Bhargav-Dave** [tattle-made/viral-spiral-backend#97]
A player should not be able to use "Mark as Fake" on cards that are true indefinitely, they should receive a penalty if they mark a TRUE card as fake.

**Comment by uudbilawmanus** [comment]
So in my mind the 'penalty' was in the way that you won't cause your opponent to lose a point if you mark a true card as fake. But i thimk i see your point - a player can simply mark every card as fake just to be safe. How about a player only gets two mark as fake once per round? So they cannot do it until their turn comes around once again?

**Comment by uudbilawmanus** [comment]
Based on the playtest, a penalty of 1 clout for marking a true card as fake makes sense. Ignore my last comment.

**Comment by Bhargav-Dave** [comment]
Agreed to this, adding one point penalty to marking incorrectly as fake
The change has been added here: https://github.com/tattle-made/viral-spiral-backend/pull/117
