### ISSUE TITLE
Sources (encyclopedia entries) of cards are not correctly linked up 

### ISSUE THREAD

**Issue by Bhargav-Dave** [tattle-made/viral-spiral-backend#98]
This bug was discovered recently where ONLY the fake versions of the encyclopedia entries are linked up to the cards. Hence, when a player checks the encyclopedia entry it is always the false entry. 

A fix needs to be created where the correct text of the card is linked to the TRUE version of the encyclopedia entry and the FAKE text of the card is linked to the FAKE version. 

1. The encyclopedia entries can be found here: 
 https://github.com/tattle-made/viral-spiral-backend/blob/main/config_jsons/example1/cards.ods 
(You may request the latest version of this file via commenting on the issue)
The entries can be found in the sheets that start with `[S]`

2. The following script converts this data into a JSON file: 
 https://github.com/tattle-made/viral-spiral-backend/blob/main/scripts/load_articles.py

3. That JSON file can be found over here: 
https://github.com/tattle-made/viral-spiral-backend/blob/main/config_jsons/example1/articles.json

4. The file that is used to convert the rest of the card related data into a JSON file is the following: 
https://github.com/tattle-made/viral-spiral-backend/blob/main/scripts/xls_to_json.py

This file contains way to differentiate between the texts of the TRUE and FAKE descriptions of the cards and saves those as separate cards, so currently a direction to work towards might be being able to use the logic that is used in `load_articles.py` inside `xls_to_json.py` and while the articles are being extracted from the data file, link their texts to the respective TRUE and FAKE descriptions that are being extracted by `xls_to_json.py`

**Comment by dennyabrain** [comment]
addressed here - 80b65e1
